packages:
  - 'examples/*'
  - 'packages/*'
catalog:
  '@pansy/shared': ^1.16.1
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@types/gulp': ^4.0.17
  '@types/gulp-concat': ^0.0.37
  '@types/gulp-header': ^2.0.4
  '@types/gulp-rename': ^2.0.6
  '@types/lodash': ^4.17.7
  antd: ^5.20.5
  dumi: ^2.4.9
  gulp: ^5.0.0
  gulp-concat: ^2.6.1
  gulp-header: ^2.0.9
  gulp-rename: ^2.0.0
  lint-staged: ^15.2.10
  lodash: ^4.17.21
  prettier: ^2.8.8
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  tsx: ^4.19.0
  typescript: ^5.5.4
  use-clipboard-hook: ^1.1.1
  zx: ^8.1.5
