packages:
  - 'examples/*'
  - 'packages/*'
  - scripts
catalog:
  '@commitlint/cli': ^19.4.1
  '@commitlint/config-conventional': ^19.4.1
  '@pansy/shared': ^1.16.1
  '@rgrove/parse-xml': ^3.0.0
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@types/svgo': ^2.6.3
  '@types/through2': ^2.0.41
  '@types/vinyl': ^2.0.12
  '@umijs/utils': ^4.3.18
  '@types/gulp': ^4.0.17
  '@types/gulp-concat': ^0.0.37
  '@types/gulp-header': ^2.0.4
  '@types/gulp-rename': ^2.0.6
  '@types/lodash': ^4.17.7
  '@types/ramda': ^0.30.2
  antd: ^5.20.5
  chalk: ^5.3.0
  cross-spawn: ^7.0.3
  dumi: ^2.4.9
  del: ^7.1.0
  father: ^4.5.0
  gulp: ^5.0.0
  gulp-concat: ^2.6.1
  gulp-header: ^2.0.9
  gulp-rename: ^2.0.0
  husky: ^9.1.5
  lerna: ^8.1.8
  lint-staged: ^15.2.10
  lodash: ^4.17.21
  prettier: ^2.8.8
  react: ^18.3.1
  react-dom: ^18.3.1
  ramda: 0.30.1
  signale: ^1.4.0
  simple-git: ^3.26.0
  svgo: ^2.8.0
  through2: ^4.0.2
  rimraf: ^6.0.1
  tsx: ^4.19.0
  typescript: ^5.5.4
  use-clipboard-hook: ^1.1.1
  vinyl: ^3.0.0
  zx: ^8.1.5
