import * as SenIcons from '@sensoro-design/icons/es/icons';

export const all = Object.keys(SenIcons)
  .map((n) => n.replace(/(Outlined|Filled|TwoTone|Purely)$/, ''))
  .filter((n, i, arr) => arr.indexOf(n) === i);

/** 方向与提示 */
const direction = [
  'Up',
  'Down',
  'Left',
  'Right',
  'ArrowUpPro',
  'ArrowDownPro',
  'ArrowLeftPro',
  'ArrowRightPro',
  'Check',
  'Close',
  'CloseCircle',
  'InfoCircle',
  'ExclamationCircle',
  'CheckCircle',
  'CaretDown',
  'CaretLeft',
  'CaretRight',
  'CaretUp',
];

/** 界面操作 */
const operation = [
  'Upload',
  'Download',
  'Minus',
  'Plus',
  'MenuUnfold',
  'MenuFold',
  'Logout',
  'Login',
  'Delete',
  'Form',
  'Swap',
  'Sort',
  'ShareAlt',
  'Batch',
  'Reload',
  'Search',
  'Holder',
  'Save',
  'Stop',
  'Clear',
  'Copy',
  'Drag',
  'Setting',
  'Star',
  'Lock',
  'Unlock',
  'Filter',
  'EyeInvisible',
  'Eye',
  'ToTop',
  'Device',
];

const empty = [
  'NoAlarm',
  'NoApp',
  'NoCar',
  'NoCars',
  'NoData',
  'NoDevice',
  'NoImage',
  'NoPerson',
  'NoPersons',
  'NoVideo',
];

/** 天气 */
const weather = [
  'Sun',
  'Sunrise',
  'Sunset',
  'HeatUp',
  'HeatDown',
  'RainfallIntensity',
  'Blizzard',
  'Rainstorm',
  'Hail',
  'LightningPro',
  'Thunderstorm',
  'WindSpeed',
  'Typhoon',
  'Leaves',
  'AirPressure',
  'Dew',
  'Haze',
  'HeavyFog',
  'WindDirection',
  'Frost',
  'Noise',
  'Drought',
  'IcyRoad',
  'ModerateRain',
];

const regionalManagement = [
  'Area',
  'AreaPlusCircle',
  'Building',
  'Unit',
  'Floor',
  'Room',
  'BuildingPlusCircle',
  'Employer',
];

/** 音影类 */
const audioVideo = [
  'Camera',
  'NoPhoto',
  'FastForward30S',
  'Rewind30S',
  'Compress',
  'Expand',
  'FullscreenPro',
  'FullscreenExitPro',
  'ZoomIn',
  'ZoomOut',
  'Mute',
  'SoundSmall',
  'Sound',
  'ApertureMinus',
  'AperturePlus',
  'ZoomMinus',
  'ZoomPlus',
  'Audio',
  'AudioMuted',
  'FocusOneKey',
  'View',
  'OriginalRatio',
  'Yuntai',
  'SplitScreen',
  'Screencast',
  'MinusCircle',
  'PlayCirclePro',
  'Kinescope',
  'KinescopeStop',
  'OfflinePro',
  'RotationClose',
  'Screenshot',
  'Rotation',
  'PauseCircle',
  'PlayCircle',
  'Video',
  'VideoStop',
  'FastBackward',
  'FastForward',
];

const gallery = [
  'ImageCamera',
  'RetrieveNonMotorVehicle',
  'RetrieveSmile',
  'RetrieveHumanoid',
  'NonMotorVehicle',
  'Car',
  'Smile',
  'RetrieveCar',
  'ImageOptimization',
  'RetrievePeople',
];

const file = [
  'FolderOpen',
  'FileUser',
  'File',
  'FilePng',
  'FileJpg',
  'FileJpeg',
  'FilePro',
  'FileSeal',
  'FileCheck',
  'FileTime',
  'FilePen',
  'FileSearch',
  'FileReport',
];

const user = [
  'User',
  'UserPlusCircle',
  'UserMinusCircle',
  'UserSafetyCertificate',
  'UserSetting',
  'UserManage',
  'UserForeign',
  'UserLeaveEarly',
  'UserVip',
  'UserTime',
  'UserExclamationCircle',
];

const device = [
  'GasSensor',
  'SmartBox',
  'LinsAccess',
  'Dormancy',
  'Controller',
  'Hydrolab',
  'SmartWatch',
  'Pm25',
  'HumanTrafficVideo',
  'Lpg',
  'TrackingDevice',
  'Pm',
  'ArcDetection',
  'DomeCamera',
  'CardReader',
  'Inclination',
  'Chip',
  'NaturalGas',
  'FireHydraulics',
  'ManholeCover',
  'Co',
  'Ch4',
  'Nh3',
  'Co2',
  'Rainfall',
  'WaterLevel',
  'O2',
  'TemperaturePatch',
  'Thermometer',
  'MercuryThermometer',
  'AudibleAlarmHost',
  'Infrared',
  'FireHost',
  'Leaking',
  'Smoke',
  'ContinuityDetection',
  'Spray',
  'DriveRecorder',
  'ManualAlarmCircle',
  'ElectricityMeter',
  'Geomagnetism',
  'BaseStation',
  'FireCamera',
  'FaceCamera',
  'AlertCamera',
  'FullTargetCamera',
  'VirtualCamera',
  'Fire',
  'Lightning',
  'SafetyCertificate',
  'GasAlarm',
  'EnvironmentalMonitoring',
  'EpidemicProtection',
  'ParkingLot',
  'SmartLightPole',
  'Aim',
  'Medical',
  'Drone',
  'IntelligentAccess',
  'SmartWaterMeter',
  'GasSensorController',
  'RemoteFireMonitoring',
  'PartlyCloudy',
  'DoorLock',
  'FireHydrant',
  'Database',
  'WeatherStation',
  'ForestFireCamera',
  'VesselIllegalWork',
  'AircircuitBreaker',
  'ElectricalFire',
  'Elevator',
  'VideoCamera',
  'WalkieTalkie',
  'GasMonitoring',
  'DronePro',
  'Play',
  'Pause',
];

const deviceStatus = [
  'Landing',
  'TakeOff',
  'SyncOn',
  'SyncOff',
  'Shutdown',
  'Leave',
  'AudibleAlarmOpen',
  'AudibleAlarmClose',
  'DoorSetting',
  'MeansAccess',
  'DormancyCancel',
  'Upgrade',
  'DeploymentUnit',
  'Poweroff',
  'Sync',
  'Square',
  'NormallyOpenCancel',
  'Wifi',
  'Muffling',
  'LowBatteryMuted',
  'PowerOutage',
  'PowerUps',
  'SafetySearch',
  'SafetyCertificateCancel',
  'PartiallyFortified',
  'Maintenance',
  'Tool',
];

const map = [
  'Compass',
  'Ruler',
  'PanoramaMap',
  'Satellite',
  'SetCenterPoint',
  'SetCenterPointChecked',
  'Block',
  'Twins',
  'Distance',
  'Vr',
  'DrawPolygon',
  'DrawRectangle',
  'DrawRound',
  'River',
  'Lake',
  'Reservoir',
  'Dam',
  'Location',
  'PanoramaTour',
  'Route',
  'HighSpeedBayonet',
  'Waters',
  'Hospital',
  'Rubbish',
  'Forest',
  'Heatmap',
];

const firefighting = [
  'WaterArea',
  'VentilationFan',
  'CommunicationEquipment',
  'FireExtinguisher',
  'FireHydrant',
  'Jack',
  'FireProofDoor',
  'PluggingEquipment',
  'FireMonitor',
  'Flashlight',
  'FireEmergencyCabinet',
  'FireHose',
  'SafetyRope',
  'FireTruck',
  'MedicalKit',
  'FireGuns',
  'PoliceBelt',
  'GasAlarm',
  'FireBrigade',
  'Firemen',
  'MiniatureFireStation',
  'Supplies',
];

const navigation = [
  'Atlas',
  'Iot',
  'HashrateCenter',
  'DataAssets',
  'GeoLocation',
  'DigitalMedia',
  'Global',
  'MoneyWatch',
  'SignalTower',
];

const universal = [
  'Plate',
  'Applets',
  'EllipsisCircle',
  'More',
  'Project',
  'Code',
  'Tag',
  'Home',
  'Banner',
  'DelayWarning',
  'Moon',
  'Current',
  'Male',
  'Woman',
  'Gender',
  'LegendPro',
  'Cake',
  'UnorderedList',
  'SerialNumber',
  'Address',
  'Collect',
  'Calendar',
  'TimeCircle',
  'Qrcode',
  'Organize',
  'Link',
  'Profile',
  'Bell',
  'PayCircle',
  'Overview',
  'Appstore',
  'Alert',
  'Message',
  'Mobile',
  'Phone',
  'Image',
];

const dataAssets = ['Garage', 'IndoorTrack', 'PersonnelDatabase', 'VehicleFile', 'Idcard'];

const otherBusiness = [
  'Layout',
  'Focus',
  'Legend',
  'Thumbnail',
  'Polymerization',
  'RingLayout',
  'MeshLayout',
  'RadiationLayout',
  'OrganizePro',
  'LicensePlate',
  'FileWarning',
  'Parabolic',
  'GroupRental',
  'HomeIsolation',
  'SmartCommunity',
  'Resource',
  'NoFishing',
  'NoSwimming',
  'KeyArea',
  'Handcuffs',
  'BloodPressure',
  'HeartRate',
  'BloodOxygen',
  'StepCount',
  'GetUp',
  'BigScreen',
  'Tetris',
  'Auth',
  'Service24Hour',
  'Insurance',
  'SafetyKey',
  'NotificationTemplate',
  'Engine',
  'Algorithm',
  'ServiceCard',
  'Shopping',
  'Lins',
  'WordOrder',
  'LineChart',
  'Key',
  'BrainMap',
  'Road',
  'Account',
  'Warning',
  'FireHazard',
  'IllegalBuilding',
  'NucleicAcid',
  'Elder',
  'Operate',
  'Tenant',
  'DataInsights',
  'SleepPro',
  'AlarmClock',
  'CalendarCheck',
  'Helmet',
  'MolecularChain',
];

const datum = [
  ...direction,
  ...audioVideo,
  ...map,
  ...regionalManagement,
  ...operation,
  ...device,
  ...deviceStatus,
  ...file,
  ...user,
  ...empty,
  ...weather,
  ...gallery,
  ...firefighting,
  ...navigation,
  ...universal,
  ...dataAssets,
  ...otherBusiness,
];

const other = all.filter((n) => !datum.includes(n));

export const categories = {
  direction,
  operation,
  file,
  user,
  device,
  deviceStatus,
  audioVideo,
  gallery,
  regionalManagement,
  weather,
  map,
  firefighting,
  navigation,
  empty,
  universal,
  dataAssets,
  otherBusiness,
  other,
};

export default categories;

export type Categories = typeof categories;
export type CategoriesKeys = keyof Categories;
