name: Deploy CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Bootstrap
        run: pnpm bootstrap

      - name: Generate
        run: pnpm generate

      - name: Build
        run: pnpm release:build

      - name: Site Build
        run: pnpm site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
